CREATE TABLE `consumer_reviews` (
  `auto_id` int(11) NOT NULL AUTO_INCREMENT,
  `id` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `dateUpdated` datetime DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `asins` varchar(255) DEFAULT NULL,
  `brand` varchar(255) DEFAULT NULL,
  `categories` varchar(2083) DEFAULT NULL,
  `primaryCategories` varchar(255) DEFAULT NULL,
  `imageURLs` text,
  `keys` varchar(2083) DEFAULT NULL,
  `manufacturer` varchar(255) DEFAULT NULL,
  `manufacturerNumber` varchar(255) DEFAULT NULL,
  `reviews.date` datetime DEFAULT NULL,
  `reviews.dateSeen` varchar(2083) DEFAULT NULL,
  `reviews.didPurchase` varchar(255) DEFAULT NULL,
  `reviews.doRecommend` varchar(255) DEFAULT NULL,
  `reviews.id` bigint(30) DEFAULT NULL,
  `reviews.numHelpful` int(11) DEFAULT NULL,
  `reviews.rating` int(11) DEFAULT NULL,
  `reviews.sourceURLs` text,
  `reviews.text` text,
  `reviews.title` varchar(255) DEFAULT NULL,
  `reviews.username` varchar(255) DEFAULT NULL,
  `sourceURLs` text,
  PRIMARY KEY (`auto_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8